version: "3.3"
services:
  nuno:
    image: "docker.nussmueller.dev/nuno-fe"
    container_name: NUNO-FE
    networks:
      - proxy
      - nuno-internal
    depends_on:
      - nuno-be
    restart: unless-stopped
  nuno-be:
    image: "docker.nussmueller.dev/nuno-be"
    container_name: NUNO-BE
    hostname: NUNO-BE
    networks:
      - nuno-internal
    depends_on:
      - nuno-db
    restart: unless-stopped
  nuno-db:
    image: "mariadb"
    container_name: NUNO-DB
    hostname: NUNO-DB
    networks:
      - nuno-internal
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "kg4vrJG!J7uNkeULfX!WcpSBuf2iTavdAR*pacB3%TxT%Kk%u%9^FzDw3Gn^Ux^Dk2i*u5qMVqP4TA2Kyzt8dVxvwrSV*W"
    restart: unless-stopped

networks:
  proxy:
    external: true
  nuno-internal:
